#!/usr/bin/env bash
#bash script that makes nginx run 'nginx' while listening on all active IPs on port 8080
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx bash -c 'service nginx start'
